### PR TITLE
Add entry for Resources Piechart and Reco event loop

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by smuzaffar** [comment]
please remove hard coded architecture strings

**Comment by gartung** [comment]
When I tried to put in arch string I got an error.

**Comment by smuzaffar** [comment]
if you need to access the arch then you need to save it in the json results e.g. see what we do for static_checks_v2 in https://raw.githubusercontent.com/cms-sw/cms-sw.github.io/master/data/merged_prs_summary.json .

**Comment by gartung** [comment]
@smuzaffar

**Comment by smuzaffar** [comment]
will merge it tomorrow so that if any thing break then I have time to look in to it and fix it if needed

**Pull request merged**
